version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: config/php/Dockerfile
    container_name: symfony_app
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      SYMFONY_ENV: dev
    depends_on:
      - db
      - redis
    networks:
      - symfony-network

  db:
    image: postgres:latest
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony-network

  redis:
    image: redis:alpine
    container_name: symfony_redis
    networks:
      - symfony-network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/app/public
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony-network

volumes:
  postgres_data:

networks:
  symfony-network:
    driver: bridge
